import { BlocksSchema } from '@/blocks/schema';
import type { Block } from '@/blocks/types';

const ts = 1713744000000;

export const partySampleBlocks: Block[] = BlocksSchema.parse([
  {
    id: 'b1',
    schemaVersion: 1,
    type: 'archetype',
    title: 'Shieldline Chorus',
    summary: 'A patient wall that sings damage back at aggressors.',
    tags: ['Anchor', 'Sustain', 'Reactive'],
    confidence: 0.82,
    status: 'draft',
    pinned: false,
    relations: [],
    position: { x: 60, y: 60 },
    size: { width: 320, height: 280 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      tagline: 'A patient wall that sings damage back at aggressors.',
      roles: [
        { name: 'Guardian', role: 'Anchor', count: 2, color: '#6d2e10' },
        { name: 'Binder', role: 'Sustainer', count: 1, color: '#3f6b4a' },
        { name: 'Hex Archer', role: 'Pressure', count: 2, color: '#4a5d8f' },
      ],
      leader: 'Banner - grants +1 Poise on held ground.',
      strengths: ['Rewards patience', 'Counters rush comps', 'Clear read'],
      weaknesses: ['Slow to relocate', 'Vulnerable to flanks'],
    },
  },
  {
    id: 'b2',
    schemaVersion: 1,
    type: 'archetype',
    title: 'Hunter Relay',
    summary: 'Mark. Chase. Execute. Keep moving.',
    tags: ['Pressure', 'Mobile', 'Combo'],
    confidence: 0.74,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'b1', kind: 'counters', note: 'Trades patience for tempo.' }],
    position: { x: 400, y: 60 },
    size: { width: 320, height: 280 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      tagline: 'Mark. Chase. Execute. Keep moving.',
      roles: [
        { name: 'Skirmisher', role: 'Pressure', count: 2, color: '#b4542a' },
        { name: 'Hex Archer', role: 'Disruptor', count: 1, color: '#4a5d8f' },
        { name: 'Field Medic', role: 'Utility', count: 1, color: '#3f6b4a' },
        { name: 'Banner', role: 'Leader', count: 1, color: '#6d2e10' },
      ],
      leader: 'Skirmisher-captain - marked enemies take +25% from allies.',
      strengths: ['Punishes isolated targets', 'High skill ceiling'],
      weaknesses: ['Crumbles if marks break', 'Soft to pressure-back'],
    },
  },
  {
    id: 'b3',
    schemaVersion: 1,
    type: 'formation',
    title: 'Three-row Anvil',
    summary: 'Front holds, mid pressures, back cycles cooldowns.',
    tags: ['Formation', 'Front-mid-back'],
    confidence: 0.78,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'b1', kind: 'references' }],
    position: { x: 740, y: 60 },
    size: { width: 320, height: 280 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      note: 'Front holds, mid pressures, back cycles cooldowns.',
      rows: [
        { label: 'Front', slots: ['Guardian', 'Guardian', 'Skirmisher'] },
        { label: 'Mid', slots: ['Hex Archer', 'Banner', 'Hex Archer'] },
        { label: 'Back', slots: ['Field Medic', 'Binder'] },
      ],
    },
  },
  {
    id: 'b4',
    schemaVersion: 1,
    type: 'graph',
    title: 'Class synergy graph',
    summary: 'A map of class affinities centered on Banner support.',
    tags: ['Synergy', 'Classes'],
    confidence: 0.7,
    status: 'draft',
    pinned: false,
    relations: [],
    position: { x: 60, y: 360 },
    size: { width: 420, height: 320 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      nodes: [
        { id: 'guardian', label: 'Guardian', x: 0.2, y: 0.25, role: 'Anchor' },
        { id: 'skirm', label: 'Skirmisher', x: 0.78, y: 0.22, role: 'Pressure' },
        { id: 'medic', label: 'Field Medic', x: 0.2, y: 0.78, role: 'Sustain' },
        { id: 'banner', label: 'Banner', x: 0.5, y: 0.5, role: 'Leader' },
        { id: 'archer', label: 'Hex Archer', x: 0.8, y: 0.75, role: 'Disrupt' },
        { id: 'binder', label: 'Binder', x: 0.5, y: 0.12, role: 'Utility' },
      ],
      edges: [
        ['guardian', 'banner', 'strong'],
        ['banner', 'skirm', 'strong'],
        ['banner', 'medic', 'strong'],
        ['banner', 'archer', 'medium'],
        ['banner', 'binder', 'medium'],
        ['guardian', 'medic', 'medium'],
        ['skirm', 'archer', 'strong'],
        ['archer', 'binder', 'weak'],
      ],
    },
  },
  {
    id: 'b5',
    schemaVersion: 1,
    type: 'table',
    title: 'Archetype comparison',
    summary: 'A comparison board for complexity, novelty, depth, readability, and risk.',
    tags: ['Compare'],
    confidence: 0.75,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'b1', kind: 'references' }, { to: 'b2', kind: 'references' }],
    position: { x: 500, y: 360 },
    size: { width: 560, height: 240 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      rows: [
        { name: 'Shieldline Chorus', complexity: 2, novelty: 3, depth: 4, readability: 5, risk: 2 },
        { name: 'Hunter Relay', complexity: 4, novelty: 4, depth: 5, readability: 3, risk: 3 },
        { name: 'Ember Circle', complexity: 3, novelty: 5, depth: 4, readability: 3, risk: 4, ghost: true },
      ],
      cols: [
        { key: 'complexity', label: 'Complexity' },
        { key: 'novelty', label: 'Novelty' },
        { key: 'depth', label: 'Tactical depth' },
        { key: 'readability', label: 'Readability' },
        { key: 'risk', label: 'Impl. risk' },
      ],
    },
  },
  {
    id: 'b6',
    schemaVersion: 1,
    type: 'flow',
    title: 'Battle behavior - Shieldline',
    summary: 'Triggers and squad responses for Shieldline battle behavior.',
    tags: ['Behavior', 'AI'],
    confidence: 0.76,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'b1', kind: 'references' }],
    position: { x: 1080, y: 60 },
    size: { width: 360, height: 380 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      branches: [
        { trigger: 'Surrounded', steps: ['Guardians pivot to face wider angle', 'Binder drops a perimeter hex', 'Medic holds line, does not advance'] },
        { trigger: 'Leader falls', steps: ['Squad drops to Poise 0', 'Nearest Guardian inherits banner for 1 round', 'Archers shift to defensive arcs'] },
        { trigger: 'Morale high', steps: ['Echo-strike triggers on reactive damage', 'Archers push range by one band'] },
      ],
    },
  },
  {
    id: 'b7',
    schemaVersion: 1,
    type: 'tradeoff',
    title: 'Tradeoffs - Hunter Relay',
    summary: 'Hunter Relay has strong burst and counter play but weak endurance.',
    tags: ['Tradeoff', 'Hunter Relay'],
    confidence: 0.72,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'b2', kind: 'references' }],
    position: { x: 1080, y: 470 },
    size: { width: 360, height: 210 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      items: [
        { label: 'Burst', value: 0.85, k: 'strong' },
        { label: 'Endurance', value: 0.35, k: 'weak' },
        { label: 'Readability', value: 0.55, k: 'med' },
        { label: 'Counter play', value: 0.7, k: 'med' },
      ],
      counters: ['Wide AoE pressure', 'Mark-breaking stealth', 'Stall comps'],
    },
  },
  {
    id: 'b8',
    schemaVersion: 1,
    type: 'note',
    title: 'Pinned - from raw context',
    summary: 'A raw-note quote about squad silhouette and tactics.',
    tags: ['Raw context'],
    confidence: 0.8,
    status: 'review',
    pinned: true,
    relations: [],
    position: { x: 500, y: 620 },
    size: { width: 280, height: 140 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'party',
    payload: {
      body: '"I want squads to FEEL different before you ever command them. The silhouette of the formation should telegraph the plan."',
    },
  },
]);
