import { BlocksSchema } from '@/blocks/schema';
import type { Block } from '@/blocks/types';

const ts = 1713744000000;

export const unitSampleBlocks: Block[] = BlocksSchema.parse([
  {
    id: 'ub1',
    schemaVersion: 1,
    type: 'unit',
    title: 'Ward Anchor',
    summary: 'A patient wall. Holds ground, dampens damage around it, pivots when pushed.',
    tags: ['Front row', 'Defensive', 'Taunt'],
    confidence: 0.88,
    status: 'approved',
    pinned: false,
    relations: [],
    position: { x: 60, y: 60 },
    size: { width: 340, height: 320 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      role: 'Anchor',
      job: 'Front-line protector',
      silhouette: 'Broad tower with a raised tower shield.',
      approved: true,
      sentToParty: false,
      risk: 'Low',
      stats: { hp: 4, atk: 2, def: 5, mov: 2, rng: 1 },
    },
  },
  {
    id: 'ub2',
    schemaVersion: 1,
    type: 'abilityKit',
    title: 'Ward Anchor - Abilities',
    summary: 'Poise-powered active and passive kit for the Ward Anchor.',
    tags: ['Abilities', 'Poise'],
    confidence: 0.84,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }],
    position: { x: 420, y: 60 },
    size: { width: 340, height: 320 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitId: 'ub1',
      unitName: 'Ward Anchor',
      resource: 'Poise (caps at 3)',
      actives: [
        { name: 'Guard Break', cost: '2 Poise', cd: '1 round', effect: 'Taunt adjacent enemies; they attack with -1 ATK for 2 rounds.', timing: 'Reactive' },
        { name: 'Plant', cost: '1 Poise', cd: '-', effect: 'Root in place. Gain +2 DEF but cannot move next turn.', timing: 'Turn start' },
      ],
      passives: [
        { name: 'Anchor Stance', effect: 'Adjacent allies take -1 damage while Anchor holds position.' },
        { name: 'Unbroken', effect: 'First hit each round ignored if below 2 HP.' },
      ],
      counters: ['Displacement', 'True damage', 'Silence'],
    },
  },
  {
    id: 'ub3',
    schemaVersion: 1,
    type: 'statProfile',
    title: 'Stat profile - Ward Anchor',
    summary: 'Defensive stat profile with low movement and melee range.',
    tags: ['Stats', 'Wall'],
    confidence: 0.86,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }],
    position: { x: 780, y: 60 },
    size: { width: 340, height: 320 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitName: 'Ward Anchor',
      stats: [
        { k: 'HP', v: 4, max: 6, base: 3, note: 'Tanky' },
        { k: 'ATK', v: 2, max: 6, base: 3, note: 'Low' },
        { k: 'DEF', v: 5, max: 6, base: 3, note: 'Peak' },
        { k: 'MOV', v: 2, max: 6, base: 3, note: 'Slow' },
        { k: 'RNG', v: 1, max: 6, base: 3, note: 'Melee' },
      ],
      power: 62,
      archetype: 'Wall',
    },
  },
  {
    id: 'ub4',
    schemaVersion: 1,
    type: 'counterMatrix',
    title: 'Counter matrix - Ward Anchor',
    summary: 'Matchup scores against likely unit counters and partners.',
    tags: ['Counters'],
    confidence: 0.72,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }],
    position: { x: 60, y: 410 },
    size: { width: 420, height: 300 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitName: 'Ward Anchor',
      matrix: [
        { vs: 'Rift Skirmisher', score: -2, note: 'Flanked before pivot' },
        { vs: 'Thread Medic', score: 1, note: 'Out-trades on sustain' },
        { vs: 'Hex Archer', score: -1, note: 'Whittles from range' },
        { vs: 'Ember Caller', score: 2, note: 'AoE bounces off Anchor Stance' },
        { vs: 'Banner', score: 0, note: 'Neutral, depends on squad' },
      ],
    },
  },
  {
    id: 'ub5',
    schemaVersion: 1,
    type: 'upgradePath',
    title: 'Upgrade path - Ward Anchor',
    summary: 'Four-tier progression from Recruit to Keepstone with a defensive branch.',
    tags: ['Progression'],
    confidence: 0.8,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }],
    position: { x: 500, y: 410 },
    size: { width: 560, height: 300 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitName: 'Ward Anchor',
      stages: [
        { tier: 'I', name: 'Recruit', req: 'Start', gives: ['HP +0', 'Guard Break'], party: 'baseline' },
        { tier: 'II', name: 'Warden', req: 'Lv 3', gives: ['DEF +1', 'Plant'], party: '+1 formation slot' },
        { tier: 'III', name: 'Bulwark', req: 'Lv 6 - hold 3 objectives', gives: ['Anchor Stance upgraded: -2 damage'], party: 'Enables "Anvil" archetype' },
        { tier: 'IV', name: 'Keepstone', req: 'Lv 9 - no retreats', gives: ['Unbroken becomes 2/round'], party: 'Counts as commander' },
      ],
      branches: [{ at: 'III', choice: ['Bulwark (def)', 'Banner-of-Iron (aura)'] }],
    },
  },
  {
    id: 'ub6',
    schemaVersion: 1,
    type: 'formationFit',
    title: 'Formation fit - Ward Anchor',
    summary: 'The Ward Anchor is strongest in front-center anvil slots.',
    tags: ['Formation', 'Fit'],
    confidence: 0.82,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }, { to: 'b1', kind: 'references' }],
    position: { x: 1080, y: 60 },
    size: { width: 340, height: 320 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitName: 'Ward Anchor',
      slots: [
        { row: 'Front', pos: 'Center', fit: 5, reason: 'Ideal - anchors line' },
        { row: 'Front', pos: 'Flank', fit: 3, reason: 'OK if paired with another Anchor' },
        { row: 'Mid', pos: 'Center', fit: 2, reason: 'Wastes DEF, no threat' },
        { row: 'Mid', pos: 'Flank', fit: 1, reason: 'Too slow to rotate' },
        { row: 'Back', pos: 'Any', fit: 0, reason: 'Do not' },
      ],
      archetypes: [
        { name: 'Shieldline Chorus', fit: 'Required' },
        { name: 'Three-row Anvil', fit: 'Required' },
        { name: 'Hunter Relay', fit: 'Poor' },
      ],
    },
  },
  {
    id: 'ub7',
    schemaVersion: 1,
    type: 'synergyLinks',
    title: 'Synergy - Ward Anchor',
    summary: 'Synergy links between Ward Anchor and support or tempo classes.',
    tags: ['Synergy'],
    confidence: 0.78,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }],
    position: { x: 1080, y: 410 },
    size: { width: 340, height: 300 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitName: 'Ward Anchor',
      links: [
        { with: 'Banner', kind: 'strong', why: 'Banner aura stacks with Anchor Stance' },
        { with: 'Thread Medic', kind: 'strong', why: 'Medic Suture loves static target' },
        { with: 'Hex Archer', kind: 'medium', why: 'Archer covers pivot gap' },
        { with: 'Rift Skirmisher', kind: 'weak', why: 'Different tempos' },
        { with: 'Binder', kind: 'medium', why: 'Perimeter hex amplifies hold' },
      ],
    },
  },
  {
    id: 'ub8',
    schemaVersion: 1,
    type: 'behaviorScript',
    title: 'Behavior - Ward Anchor',
    summary: 'Autonomous behavior rules and intent verbs for the Ward Anchor.',
    tags: ['Behavior', 'AI'],
    confidence: 0.75,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }],
    position: { x: 60, y: 740 },
    size: { width: 600, height: 260 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitName: 'Ward Anchor',
      rules: [
        { when: 'Enemy enters adjacent tile', then: 'Trigger Guard Break if Poise >= 2' },
        { when: 'Ally below 30% HP adjacent', then: 'Stay planted, do not chase' },
        { when: 'Flanked from 2+ sides', then: 'Pivot to wider angle, lose 1 Poise' },
        { when: 'Leader falls', then: 'Inherit banner, +1 Poise regen for 1 round' },
      ],
      intents: ['Hold', 'Press', 'Fallback'],
    },
  },
  {
    id: 'ub9',
    schemaVersion: 1,
    type: 'riskNote',
    title: 'Impl. risk - Ward Anchor',
    summary: 'Implementation risks for the Ward Anchor pivot, aura, UI, and balance.',
    tags: ['Risk'],
    confidence: 0.7,
    status: 'draft',
    pinned: false,
    relations: [{ to: 'ub1', kind: 'references' }],
    position: { x: 690, y: 740 },
    size: { width: 330, height: 260 },
    createdAt: ts,
    updatedAt: ts,
    domain: 'unit',
    payload: {
      unitName: 'Ward Anchor',
      level: 'Medium',
      factors: [
        { label: 'AI Pivot cost', weight: 3, note: 'Pathing rewrite to re-face' },
        { label: 'Anchor Stance FX', weight: 2, note: 'Needs readable radius' },
        { label: 'Poise UI', weight: 2, note: 'Shared w/ Banner' },
        { label: 'Balance tuning', weight: 3, note: '+DEF inflation risk' },
      ],
      blockers: ['Needs pivot animation', 'Needs aura radius VFX'],
    },
  },
]);
